language: android

jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra

env:
  - TERM=dumb

script:
  - ./gradlew assembleRelease